[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' *.googleapis.com *.gstatic.com; form-action 'self'; script-src 'self' *.googletagmanager.com; connect-src 'self' *.arcana.network *.google-analytics.com *.sentry.io; img-src *; base-uri 'self';"
