[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; style-src 'self *.googleapis.com'; form-action 'self'; script-src 'self *.googletagmanager.com'; connect-src 'self'; img-src *; base-uri 'self';"
