<script lang="ts" setup>
import { useStore } from 'vuex'

import SettingCard from '@/components/app-configure/SettingCard.vue'
import VCard from '@/components/lib/VCard/VCard.vue'
import VStack from '@/components/lib/VStack/VStack.vue'
import copyToClipboard from '@/utils/copyToClipboard'

const store = useStore()
</script>

<template>
  <section name="redirect-uri">
    <SettingCard>
      <template #title>Redirect URI</template>
      <template #controls>
        <VCard variant="elevated" class="redirect-uri-card">
          <VStack
            align="center"
            justify="space-between"
            class="flex-grow redirect-uri-container"
          >
            <span
              class="body-1 text-ellipsis redirect-uri"
              :title="store.getters.redirectUri"
              >{{ store.getters.redirectUri }}</span
            >
            <img
              src="@/assets/iconography/copy.svg"
              class="cursor-pointer copy-icon"
              @click.stop="copyToClipboard(store.getters.redirectUri)"
            />
          </VStack>
        </VCard>
      </template>
      <template #description
        >URL auto-generated by Arcana to complete OAuth verification. It needs
        to be added in redirectUrl for all the verifiers you want to
        support</template
      >
    </SettingCard>
  </section>
</template>

<style scoped>
.redirect-uri-card {
  width: 20rem;
  padding: 0.75rem 1.5rem;
  border-radius: 10px;
}

.redirect-uri-container {
  width: 20rem;
}

.redirect-uri {
  width: (100% - 2rem);
}
</style>
