<script lang="ts" setup>
import SettingCard from '@/components/app-configure/SettingCard.vue'
import VCard from '@/components/lib/VCard/VCard.vue'
import VStack from '@/components/lib/VStack/VStack.vue'
import { useToast } from '@/components/lib/VToast'
import { useAppsStore } from '@/stores/apps.store'
import { useAppId } from '@/use/getAppId'
import copyToClipboard from '@/utils/copyToClipboard'

const toast = useToast()
const appsStore = useAppsStore()
const appId = useAppId()

const redirectUri = appsStore.app(appId).auth.redirectUri

async function copyRedirectUri() {
  try {
    await copyToClipboard(redirectUri)
    toast.success('Copied Redirect URI to clipboard')
  } catch (e) {
    toast.error('Unable to copy. Please try again or contact support')
  }
}
</script>

<template>
  <section name="redirect-uri">
    <SettingCard>
      <template #title>Redirect URI</template>
      <template #controls>
        <VCard variant="depressed" class="redirect-uri-card">
          <VStack
            align="center"
            justify="space-between"
            class="flex-grow redirect-uri-container"
          >
            <span
              class="body-1 text-ellipsis redirect-uri"
              :title="redirectUri"
              >{{ redirectUri }}</span
            >
            <img
              src="@/assets/iconography/copy.svg"
              class="cursor-pointer copy-icon"
              @click.stop="copyRedirectUri"
            />
          </VStack>
        </VCard>
      </template>
      <template #description
        >URL auto-generated by Arcana to complete OAuth verification. It needs
        to be added in redirectUrl for all the verifiers you want to
        support.</template
      >
    </SettingCard>
  </section>
</template>

<style scoped>
.redirect-uri-card {
  width: 20rem;
  padding: 0.75rem 1.5rem;
  border-radius: 10px;
}

.redirect-uri-container {
  width: 20rem;
}

.redirect-uri {
  width: calc(100% - 2rem);
}
</style>
